spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: uaa
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
  servlet:
    context-path: /uaa
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
