spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    session:
      timeout: 30m
